### ISSUE TITLE
Meeting Minute 6月2023

### ISSUE THREAD

**Issue by Cendikiaabdi** [hirodaisohaken/website#35]
- Hadron Physics Introduction
  (Abdi make introduction => Check to Prof. Nonaka => JP translation ask Kuroiwa-san)
- Member JP kanji (copy paste from the old website)
  (Albertus-san)

- Curriculum 
  => layout we use the old layout (Abdi)
  => Content (new content)
	M2 (Abdi)
	B4 (Ji)
- Campus life
  => Layout (Abdi)
  => copy from original website (Everyone)
	(Except from summer party 10月)
	9月 Change soken to sohaken
  => En translation later
  => ある一日の過ごし方 (daily life) save data but not show in the new webpage.
- Accomodation (Abdi)
  => Redirect to a better 3rd party application (google map search for hotel around Hiroshima university)
- Links
  => Layout (Abdi)
  => Content (Everyone)
  	=> copy from original website
  	=> e-print archive => arXiv
  	=> SLAC SPIRES => INSPIRE
  	=> discard HEPDOC search (obsolete)
  	=> HEP data (https://www.hepdata.net/) from LHC
  	=> JPS website new URL (https://jps.or.jp/)
  	=> 研究機関 too difficult to maintain
  	=> 雑誌 add the PR.C PTEP
    	=> New link for the High energy astrophysics (http://www-heaf.astro.hiroshima-u.ac.jp/index.html)
     	   Remove 素粒子実験
  	=> New link for the Quark Group (https://www.quark.hiroshima-u.ac.jp/)
  	=>  Discard 大学生協京都事業連合 --生協チャンネル--
  	=> wpl (https://wpi-skcm2.hiroshima-u.ac.jp)
  	
- SSI
  => Layout (Abdi)
  => Copy from the old website (Everyone)
  => Redirect to the newer SSI webpage (if exists)
     Ask (2022 => Kuroiwa-san. 2023 => Kabayama-san)

- Member 
  => Remove 分野
  => Leave the email address blank for now (student number)
  => Replace email addess student number => name (ask in lab meeting)

**Comment by Cendikiaabdi** [comment]
Change config main address from
github,sohaken,io => http://theo.phys.sci.hiroshima-u.ac.jp/~sohaken/NewPage/

**Comment by ahariwangsa** [comment]
I have removed 分野 and Leave the email address blank for now (student number)

**Comment by Cendikiaabdi** [comment]
Archived
